//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DomainModels.DTO.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OnlineShopEntities : DbContext
    {
        public OnlineShopEntities()
            : base("name=OnlineShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<OrderMaster> OrderMaster { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductCategory> ProductCategory { get; set; }
    
        public virtual int usp_DeleteFromCategory(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteFromCategory", idParameter);
        }
    
        public virtual int usp_DeleteFromCustomer(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteFromCustomer", idParameter);
        }
    
        public virtual int usp_DeleteFromProduct(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteFromProduct", idParameter);
        }
    
        public virtual int usp_InsertCustomerInfo(string firstName, string lastName, string adrs, string city, string region, string country, string postalCode, string phone, string email)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var adrsParameter = adrs != null ?
                new ObjectParameter("adrs", adrs) :
                new ObjectParameter("adrs", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var regionParameter = region != null ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(string));
    
            var postalCodeParameter = postalCode != null ?
                new ObjectParameter("postalCode", postalCode) :
                new ObjectParameter("postalCode", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertCustomerInfo", firstNameParameter, lastNameParameter, adrsParameter, cityParameter, regionParameter, countryParameter, postalCodeParameter, phoneParameter, emailParameter);
        }
    
        public virtual int usp_InsertProductCategoryInfo(string categoryName)
        {
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("categoryName", categoryName) :
                new ObjectParameter("categoryName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertProductCategoryInfo", categoryNameParameter);
        }
    
        public virtual int usp_InsertProductInfo(string productName, string productDescription, Nullable<decimal> unitPrice, Nullable<int> category_Ref)
        {
            var productNameParameter = productName != null ?
                new ObjectParameter("productName", productName) :
                new ObjectParameter("productName", typeof(string));
    
            var productDescriptionParameter = productDescription != null ?
                new ObjectParameter("productDescription", productDescription) :
                new ObjectParameter("productDescription", typeof(string));
    
            var unitPriceParameter = unitPrice.HasValue ?
                new ObjectParameter("unitPrice", unitPrice) :
                new ObjectParameter("unitPrice", typeof(decimal));
    
            var category_RefParameter = category_Ref.HasValue ?
                new ObjectParameter("category_Ref", category_Ref) :
                new ObjectParameter("category_Ref", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertProductInfo", productNameParameter, productDescriptionParameter, unitPriceParameter, category_RefParameter);
        }
    
        public virtual int usp_UpdateCategory(Nullable<int> id, string categoryName)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("categoryName", categoryName) :
                new ObjectParameter("categoryName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateCategory", idParameter, categoryNameParameter);
        }
    
        public virtual int usp_UpdateCustomer(Nullable<int> id, string firstName, string lastName, string adrs, string city, string region, string country, string postalCode, string phone, string email)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var adrsParameter = adrs != null ?
                new ObjectParameter("adrs", adrs) :
                new ObjectParameter("adrs", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var regionParameter = region != null ?
                new ObjectParameter("region", region) :
                new ObjectParameter("region", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(string));
    
            var postalCodeParameter = postalCode != null ?
                new ObjectParameter("postalCode", postalCode) :
                new ObjectParameter("postalCode", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateCustomer", idParameter, firstNameParameter, lastNameParameter, adrsParameter, cityParameter, regionParameter, countryParameter, postalCodeParameter, phoneParameter, emailParameter);
        }
    
        public virtual int usp_UpdateProduct(Nullable<int> id, string productName, string productDescription, Nullable<decimal> unitPrice, Nullable<int> category_Ref)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("productName", productName) :
                new ObjectParameter("productName", typeof(string));
    
            var productDescriptionParameter = productDescription != null ?
                new ObjectParameter("productDescription", productDescription) :
                new ObjectParameter("productDescription", typeof(string));
    
            var unitPriceParameter = unitPrice.HasValue ?
                new ObjectParameter("unitPrice", unitPrice) :
                new ObjectParameter("unitPrice", typeof(decimal));
    
            var category_RefParameter = category_Ref.HasValue ?
                new ObjectParameter("category_Ref", category_Ref) :
                new ObjectParameter("category_Ref", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateProduct", idParameter, productNameParameter, productDescriptionParameter, unitPriceParameter, category_RefParameter);
        }
    
        public virtual int usp_OrderDetails_Delet(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_OrderDetails_Delet", idParameter);
        }
    
        public virtual int usp_OrderDetails_Insert(Nullable<decimal> unitPrice, Nullable<decimal> discount, Nullable<decimal> taxRate, Nullable<int> quantity, Nullable<int> product_Ref, Nullable<int> orderMaster_Ref)
        {
            var unitPriceParameter = unitPrice.HasValue ?
                new ObjectParameter("unitPrice", unitPrice) :
                new ObjectParameter("unitPrice", typeof(decimal));
    
            var discountParameter = discount.HasValue ?
                new ObjectParameter("discount", discount) :
                new ObjectParameter("discount", typeof(decimal));
    
            var taxRateParameter = taxRate.HasValue ?
                new ObjectParameter("taxRate", taxRate) :
                new ObjectParameter("taxRate", typeof(decimal));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var product_RefParameter = product_Ref.HasValue ?
                new ObjectParameter("product_Ref", product_Ref) :
                new ObjectParameter("product_Ref", typeof(int));
    
            var orderMaster_RefParameter = orderMaster_Ref.HasValue ?
                new ObjectParameter("orderMaster_Ref", orderMaster_Ref) :
                new ObjectParameter("orderMaster_Ref", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_OrderDetails_Insert", unitPriceParameter, discountParameter, taxRateParameter, quantityParameter, product_RefParameter, orderMaster_RefParameter);
        }
    
        public virtual int usp_OrderDetails_Update(Nullable<int> id, Nullable<decimal> unitPrice, Nullable<decimal> discount, Nullable<decimal> taxRate, Nullable<int> quantity, Nullable<int> product_Ref, Nullable<int> orderMaster_Ref)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var unitPriceParameter = unitPrice.HasValue ?
                new ObjectParameter("unitPrice", unitPrice) :
                new ObjectParameter("unitPrice", typeof(decimal));
    
            var discountParameter = discount.HasValue ?
                new ObjectParameter("discount", discount) :
                new ObjectParameter("discount", typeof(decimal));
    
            var taxRateParameter = taxRate.HasValue ?
                new ObjectParameter("taxRate", taxRate) :
                new ObjectParameter("taxRate", typeof(decimal));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var product_RefParameter = product_Ref.HasValue ?
                new ObjectParameter("product_Ref", product_Ref) :
                new ObjectParameter("product_Ref", typeof(int));
    
            var orderMaster_RefParameter = orderMaster_Ref.HasValue ?
                new ObjectParameter("orderMaster_Ref", orderMaster_Ref) :
                new ObjectParameter("orderMaster_Ref", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_OrderDetails_Update", idParameter, unitPriceParameter, discountParameter, taxRateParameter, quantityParameter, product_RefParameter, orderMaster_RefParameter);
        }
    
        public virtual int usp_OrderMaster_Delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_OrderMaster_Delete", idParameter);
        }
    
        public virtual int usp_OrderMaster_Insert(Nullable<System.DateTime> orderDate, Nullable<int> customer_Ref)
        {
            var orderDateParameter = orderDate.HasValue ?
                new ObjectParameter("orderDate", orderDate) :
                new ObjectParameter("orderDate", typeof(System.DateTime));
    
            var customer_RefParameter = customer_Ref.HasValue ?
                new ObjectParameter("customer_Ref", customer_Ref) :
                new ObjectParameter("customer_Ref", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_OrderMaster_Insert", orderDateParameter, customer_RefParameter);
        }
    
        public virtual int usp_OrderMaster_Update(Nullable<int> id, Nullable<System.DateTime> orderDate, Nullable<int> customer_Ref)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var orderDateParameter = orderDate.HasValue ?
                new ObjectParameter("orderDate", orderDate) :
                new ObjectParameter("orderDate", typeof(System.DateTime));
    
            var customer_RefParameter = customer_Ref.HasValue ?
                new ObjectParameter("customer_Ref", customer_Ref) :
                new ObjectParameter("customer_Ref", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_OrderMaster_Update", idParameter, orderDateParameter, customer_RefParameter);
        }
    
        public virtual int usp_OrderMasterDetails_Insert(Nullable<int> orderCode, Nullable<System.DateTime> orderDate, Nullable<int> customer_Ref)
        {
            var orderCodeParameter = orderCode.HasValue ?
                new ObjectParameter("orderCode", orderCode) :
                new ObjectParameter("orderCode", typeof(int));
    
            var orderDateParameter = orderDate.HasValue ?
                new ObjectParameter("orderDate", orderDate) :
                new ObjectParameter("orderDate", typeof(System.DateTime));
    
            var customer_RefParameter = customer_Ref.HasValue ?
                new ObjectParameter("customer_Ref", customer_Ref) :
                new ObjectParameter("customer_Ref", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_OrderMasterDetails_Insert", orderCodeParameter, orderDateParameter, customer_RefParameter);
        }
    
        public virtual int usp_OrderMasterDetails_Update(Nullable<int> idMaster, Nullable<int> orderCode, Nullable<System.DateTime> orderDate, Nullable<int> customer_Ref)
        {
            var idMasterParameter = idMaster.HasValue ?
                new ObjectParameter("idMaster", idMaster) :
                new ObjectParameter("idMaster", typeof(int));
    
            var orderCodeParameter = orderCode.HasValue ?
                new ObjectParameter("orderCode", orderCode) :
                new ObjectParameter("orderCode", typeof(int));
    
            var orderDateParameter = orderDate.HasValue ?
                new ObjectParameter("orderDate", orderDate) :
                new ObjectParameter("orderDate", typeof(System.DateTime));
    
            var customer_RefParameter = customer_Ref.HasValue ?
                new ObjectParameter("customer_Ref", customer_Ref) :
                new ObjectParameter("customer_Ref", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_OrderMasterDetails_Update", idMasterParameter, orderCodeParameter, orderDateParameter, customer_RefParameter);
        }
    
        public virtual int usp_OrderMasterDetails_Delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_OrderMasterDetails_Delete", idParameter);
        }
    
        public virtual ObjectResult<Customer> usp_Customer_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Customer>("usp_Customer_Select");
        }
    
        public virtual ObjectResult<Customer> usp_Customer_Select(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Customer>("usp_Customer_Select", mergeOption);
        }
    
        public virtual ObjectResult<ProductCategory> usp_ProductCategory_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductCategory>("usp_ProductCategory_Select");
        }
    
        public virtual ObjectResult<ProductCategory> usp_ProductCategory_Select(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductCategory>("usp_ProductCategory_Select", mergeOption);
        }
    
        public virtual ObjectResult<Product> usp_Product_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Product>("usp_Product_Select");
        }
    
        public virtual ObjectResult<Product> usp_Product_Select(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Product>("usp_Product_Select", mergeOption);
        }
    
        public virtual ObjectResult<usp_Product_SelectWithCategoryCode_Result> usp_Product_SelectWithCategoryCode()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Product_SelectWithCategoryCode_Result>("usp_Product_SelectWithCategoryCode");
        }
    
        public virtual ObjectResult<usp_SelectCustomerInfo_Result1> usp_SelectCustomerInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SelectCustomerInfo_Result1>("usp_SelectCustomerInfo");
        }
    
        public virtual ObjectResult<usp_SelectProductInfo_Result1> usp_SelectProductInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SelectProductInfo_Result1>("usp_SelectProductInfo");
        }
    
        public virtual ObjectResult<usp_SelectCategoryCode_Result> usp_SelectCategoryCode()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SelectCategoryCode_Result>("usp_SelectCategoryCode");
        }
    
        public virtual ObjectResult<Customer> usp_SelectCustomerNameGivenId(Nullable<int> id, ObjectParameter firstName, ObjectParameter lastName)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Customer>("usp_SelectCustomerNameGivenId", idParameter, firstName, lastName);
        }
    
        public virtual ObjectResult<Customer> usp_SelectCustomerNameGivenId(Nullable<int> id, ObjectParameter firstName, ObjectParameter lastName, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Customer>("usp_SelectCustomerNameGivenId", mergeOption, idParameter, firstName, lastName);
        }
    
        public virtual ObjectResult<usp_GetOrderDetailsGivenOrderMasterId_Result2> usp_GetOrderDetailsGivenOrderMasterId(Nullable<int> orderMasterId)
        {
            var orderMasterIdParameter = orderMasterId.HasValue ?
                new ObjectParameter("orderMasterId", orderMasterId) :
                new ObjectParameter("orderMasterId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetOrderDetailsGivenOrderMasterId_Result2>("usp_GetOrderDetailsGivenOrderMasterId", orderMasterIdParameter);
        }
    
        public virtual ObjectResult<Product> usp_SelectProductNameGivenId(Nullable<int> id, ObjectParameter productName)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Product>("usp_SelectProductNameGivenId", idParameter, productName);
        }
    
        public virtual ObjectResult<Product> usp_SelectProductNameGivenId(Nullable<int> id, ObjectParameter productName, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Product>("usp_SelectProductNameGivenId", mergeOption, idParameter, productName);
        }
    
        public virtual int usp_GenerateCodeForOrder(ObjectParameter orderCode)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GenerateCodeForOrder", orderCode);
        }
    
        public virtual ObjectResult<usp_OrderMaster_Select_Result2> usp_OrderMaster_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_OrderMaster_Select_Result2>("usp_OrderMaster_Select");
        }
    }
}
