//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DomainModels.DTO.EF
{
    using System;
    
    public partial class usp_SelectCustomerInfo_Result1
    {
        public int Id { get; set; }
        public Nullable<int> CustomerCode { get; set; }
    }
}
